export const ADICIONA_PROJETO = "ADICIONA_PROJETO";
export const ALTERA_PROJETO = "ALTERA_PROJETO";
export const EXCLUIR_PROJETO = "EXCLUIR_PROJETO";
export const NOTIFICAR = "NOTIFICAR";
export const DEFINIR_PROJETOS = "DEFINIR_PROJETOS";

export const DEFINIR_TAREFAS = "DEFINIR_TAREFAS";
export const ADICIONAR_TAREFA = "ADICIONAR_TAREFA";
export const ALTERA_TAREFA = "ALTERA_TAREFA";

export const DEFINIR_EXCECOES = "DEFINIR_EXCECOES";
export const DEFINIR_CAUSARAIZ = "DEFINIR_CAUSARAIZ";
export const DEFINIR_CLASSE = "DEFINIR_CLASSE";
