export const NOTIFICAR = "NOTIFICAR";
export const DEFINIR_EXCECOES = "DEFINIR_EXCECOES";
export const DEFINIR_CAUSARAIZ = "DEFINIR_CAUSARAIZ";
export const DEFINIR_CLASSE = "DEFINIR_CLASSE";
export const EXCLUIR_EXCEPTION = "EXCLUIR_EXCEPTION";
